config/routes.rb
Rails.application.routes.draw do
 resources :twitters
 root to: 'twitters#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter.rb
class Twitter < ApplicationRecord
    validates :content, presence: true
    validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
    before_action :set_twitter, only: [:show, :edit, :update, :destroy]
  def index
    @twitters = Twitter.all
  end

  def new
    if params[:back]
      @twitter = Twitter.new(blog_params)
    else
      @twitter = Twitter.new
    end
  end

  def create
    @twitter = Twitter.new(twitter_params)
    if @twitter.save
      redirect_to twitters_path, notice: "ツイートを作成しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def show
   @twitter = Twitter.find(params[:id])
end
def update
    if @twitter.update(twitter_params)
      redirect_to twitters_path, notice: "ツイートを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @twitter.destroy
    redirect_to twitters_path, notice:"ツイートを削除しました！"
  end

  private
    def twitter_params
      params.require(:twitter).permit(:content)
    end

    def set_twitter
      @twitter = Twitter.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <%= image_tag 'he.png' %>
    <br>
    <%= link_to "twitter一覧画面にもどる", twitters_path %>
    <%= link_to "投稿する", new_twitter_path %>
  </header>
  <%= yield %>

  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: @twitter, local: true) do |form| %>
  <% if @twitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= @twitter.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @twitter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="twitter_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "twitter一覧画面にもどる", twitters_path %>

app/views/twitters/edit.html.erb
<h2>ツイートを編集する</h2>
  <%= render 'form' %>

app/views/twitters/index.html.erb
<h1>ツイート一覧</h1>

<table>
  <tr>
    <th>内容</th>
  </tr>

<% @twitters.each do |twitter| %>
  <tr>
    <td><%= twitter.content %></td>
    <td><%= link_to '詳細を確認する', twitter_path(twitter.id) %></td>
    <td><%= link_to "ツイートを編集する", edit_twitter_path(twitter.id) %></td>
    <td><%= link_to "ツイートを削除する",  twitter, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </tr>
<% end %>
</table>

app/views/twitters/new.html.erb
<h2>twitterを作成する</h2>

 <%= render 'form' %>

app/views/twitters/show.html.erb
<h1>twitter詳細画面</h1>
<p>内容: <%= @twitter.content %></p>